name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.0.1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run merge script
        run: |
          pwsh -File "app\MergeScripts.ps1 -version $env:GITHUB_REF_NAME"  

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: KubeDeck Launcher ${{ github.ref_name }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: |
          pwsh -File "app\LaunchKubeDeck_v*.ps1 -version $env:GITHUB_REF_NAME"
